import { NextRequest, NextResponse } from 'next/server';
import { supabaseAdmin } from '@/lib/supabase';

function generatePDFContent(attempt: any, payment: any): string {
  return `
IQ Test Report
===============

Test ID: ${attempt.id}
Date: ${new Date(attempt.created_at).toLocaleDateString()}
Score: ${attempt.score}/100
Percentile: ${attempt.percentile}%

Answers: ${attempt.answers.join(', ')}

Payment Status: ${payment ? 'Paid' : 'Unpaid'}
${payment ? `Amount: €${(payment.amount / 100).toFixed(2)}` : ''}
${payment ? `Payment Date: ${new Date(payment.updated_at).toLocaleDateString()}` : ''}

Detailed Analysis:
------------------
Your score of ${attempt.score} places you in the ${attempt.percentile}th percentile.
This means you scored higher than ${attempt.percentile}% of test takers.

Recommendations:
1. Practice logical reasoning puzzles
2. Try memory exercises
3. Consider retesting in 3 months

Report generated by IQDecoder
https://iqdecoder.com
`;
}

export async function GET(
  request: NextRequest,
  { params }: { params: Promise<{ attemptId: string }> }
) {
  try {
    const { attemptId } = await params;
    const token = request.nextUrl.searchParams.get('token');
    
    if (!token) {
      return NextResponse.json(
        { error: 'Token required' },
        { status: 401 }
      );
    }

    // Decode token (simple base64 encoding of attemptId:email)
    const decoded = Buffer.from(token, 'base64').toString('utf-8');
    const [tokenAttemptId, email] = decoded.split(':');
    
    if (tokenAttemptId !== attemptId) {
      return NextResponse.json(
        { error: 'Invalid token' },
        { status: 401 }
      );
    }

    // Verify payment
    const { data: payment } = await supabaseAdmin
      .from('payments')
      .select('*')
      .eq('attempt_id', attemptId)
      .eq('status', 'succeeded')
      .single();

    if (!payment) {
      return NextResponse.json(
        { error: 'Payment required' },
        { status: 402 }
      );
    }

    // Get attempt
    const { data: attempt } = await supabaseAdmin
      .from('attempts')
      .select('*')
      .eq('id', attemptId)
      .single();

    if (!attempt) {
      return NextResponse.json(
        { error: 'Attempt not found' },
        { status: 404 }
      );
    }

    // Update report access count
    await supabaseAdmin
      .from('reports')
      .update({
        accessed_count: (attempt.accessed_count || 0) + 1,
      })
      .eq('attempt_id', attemptId);

    // Generate PDF content
    const pdfContent = generatePDFContent(attempt, payment);
    
    // Return as text file (simplified - in production would generate actual PDF)
    return new NextResponse(pdfContent, {
      headers: {
        'Content-Type': 'application/pdf',
        'Content-Disposition': `attachment; filename="iq-report-${attemptId}.pdf"`,
      },
    });

  } catch (error) {
    console.error('PDF generation error:', error);
    return NextResponse.json(
      { error: 'Internal server error' },
      { status: 500 }
    );
  }
}
