import { NextRequest, NextResponse } from 'next/server';
import Stripe from 'stripe';
import { supabaseAdmin } from '@/lib/supabase';

const stripe = new Stripe(process.env.STRIPE_SECRET_KEY || '', {
  apiVersion: '2025-03-31.basil',
});

const webhookSecret = process.env.STRIPE_WEBHOOK_SECRET || '';

export async function POST(request: NextRequest) {
  const body = await request.text();
  const signature = request.headers.get('stripe-signature') || '';

  let event: Stripe.Event;

  try {
    event = stripe.webhooks.constructEvent(body, signature, webhookSecret);
  } catch (err) {
    console.error('Webhook signature verification failed:', err);
    return NextResponse.json(
      { error: 'Webhook signature verification failed' },
      { status: 400 }
    );
  }

  try {
    switch (event.type) {
      case 'checkout.session.completed': {
        const session = event.data.object as Stripe.Checkout.Session;
        
        const attemptId = session.metadata?.attempt_id;
        const sessionId = session.metadata?.session_id;
        
        if (!attemptId) {
          console.error('No attempt_id in session metadata');
          break;
        }

        // Update payment status
        const { error: paymentError } = await supabaseAdmin
          .from('payments')
          .update({
            status: 'succeeded',
            email_sent: false, // Will be sent by email job
            updated_at: new Date().toISOString(),
          })
          .eq('stripe_checkout_session_id', session.id);

        if (paymentError) {
          console.error('Failed to update payment:', paymentError);
        }

        // Create report entry
        const { data: payment } = await supabaseAdmin
          .from('payments')
          .select('id')
          .eq('stripe_checkout_session_id', session.id)
          .single();

        if (payment) {
          const { error: reportError } = await supabaseAdmin
            .from('reports')
            .insert({
              attempt_id: attemptId,
              payment_id: payment.id,
              pdf_url: null, // Will be generated by PDF service
              pdf_storage_path: null,
              expires_at: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000).toISOString(),
            });

          if (reportError) {
            console.error('Failed to create report:', reportError);
          }
        }

        console.log(`Payment succeeded for attempt ${attemptId}, session ${session.id}`);
        break;
      }

      case 'checkout.session.expired':
      case 'checkout.session.async_payment_failed': {
        const session = event.data.object as Stripe.Checkout.Session;
        
        await supabaseAdmin
          .from('payments')
          .update({
            status: 'failed',
            updated_at: new Date().toISOString(),
          })
          .eq('stripe_checkout_session_id', session.id);
        
        console.log(`Payment failed for session ${session.id}`);
        break;
      }

      default:
        console.log(`Unhandled event type: ${event.type}`);
    }

    return NextResponse.json({ received: true });
  } catch (error) {
    console.error('Webhook processing error:', error);
    return NextResponse.json(
      { error: 'Webhook processing failed' },
      { status: 500 }
    );
  }
}
